### ISSUE TITLE
Video feed

### ISSUE THREAD

**Issue by mastrup** [ThijsRay/podimo#11]
I don't know if this is a bit out of scope for the intention of this great project, but here goes:

More and more podcasts on Podimo is starting to include video as an alternative to the normal podcast.
Podimo just recently introduced video as an option in the web player, so I guess it is possible to fetch the `.m3u8` link from each podcast episode and build a video-podcast feed from that?

I have already tried mocking a simple xml feed with a direct  `.m3u8` link before it expired and it is possible to play - At least from the native iOS podcast app.

**Comment by ThijsRay** [comment]
Thank you for opening the issue! I feel like this is indeed a bit out of the scope of this project. My main reason for building this is to make it possible to listen Podimo-only podcasts in other players, by converting it into a standardized format. I personally don't have a need for a video feed, but if you or others find this useful, please don't hesitate to open a pull request!

As a sidenote: [someone made this tool a few months ago](https://github.com/JoepdeJong/moviepo), that allows you to watch Podimo videos in your browser or via picture-in-picture mode. It might be what you are looking for!

**Comment by mastrup** [comment]
I understand.
Your link to [Moviepo](https://sjoemelsoftware.nl/moviepo/) is just what I was looking for - Thanks!
