### ISSUE TITLE
Not all episodes are shown

### ISSUE THREAD

**Issue by Diemertje** [ThijsRay/podimo#12]
Hi,
Not all episodes are shown, even after I changed the limit in main.py to 999

**Comment by ThijsRay** [comment]
If changing the limit doesn't work, then there might be a limit on Podimo's side. Do you have an example podcast ID where the amount of episodes exceeds the limit?

**Comment by Diemertje** [comment]
Hi

For example https://podimo.com/nl/shows/96e3cb62-6010-4bb9-a217-248c2316746d

Or

https://podimo.com/nl/shows/277309a7-5632-4e73-9cc3-aaac27b882bc

**Comment by Diemertje** [comment]
Hi ThijsRay,

Did you find the cause and maybe the solution?

**Comment by ThijsRay** [comment]
I have set the limit to a higher value and that does seem to work for me. The current hardcoded limit is 500 episodes, and there are slightly more than 500 episodes actually available in the two podcasts that you linked.
Setting https://github.com/ThijsRay/podimo/blob/157caf3ad559e09dcee1958fa2e32d0c600eabb5/main.py#L391 to something like 1000 does work for me.

**Comment by pven** [comment]
I have the same issue. Any idea what can be wrong? (I am using the online version, but maybe I should host it on my own side.)

**Comment by ThijsRay** [comment]
You can change the value to something higher if you host it yourself. I might change it in the online version in the future, but that would probably require a bit more caching to reduce the amount of traffic that gets send to Podimo's servers.

**Comment by pven** [comment]
I removed some podcasts with a lot of episodes (headlines for example), but the new episodes are not popping up. Am I still using too much? It's hard to find this out.

( I try to host it myself, but I get stuck after copying the templates. Need to look further into that. )

**Comment by ThijsRay** [comment]
Podimo has taken some countermeasures against automated programs that query their servers, like this tool does. That might be the reason why newer episodes are not showing up. I'm looking for a workaround, but that might take a while. Podimo doesn't publicly describe what heuristics are used to determine whether a request comes from a bot or not, so this takes some trial and error (and these heuristics can change at any moment) 

In the meantime, you might have more success with self hosting it. Issue https://github.com/ThijsRay/podimo/issues/13 mentions a workaround. I couldn't get it to work on podimo.thijs.sh, but it might work for self hosted instances.

**Comment by pven** [comment]
I just got some notificatons in Pocket Casts for new Podimo-episodes. Was something fixed? :-)

**Comment by pven** [comment]
Too bad ... it is not working anymore. (I am going to run it locally.)
