### ISSUE TITLE
Feature request: Ability to select danish area codes in the UI

### ISSUE THREAD

**Issue by alego500** [ThijsRay/podimo#18]
Podimo also has exclusive podcasts in Denmark. Because of this it would be nice to be able to select the danish error code in the menu.

Right now, I cannot test this, because i'm not self hosting and the public host is blocked (as understood from #17 ), but if I remember correctly, from when the service worked I can confirm that a danish Podimo exclusive podcast indeed does load without the proper area code.

**Comment by ThijsRay** [comment]
Hi @alego500, I've added a Danish region code to the drop down menu. Hopefully that solves the issue for you.
