### ISSUE TITLE
Erorr in AuthorizationPreregisterUser

### ISSUE THREAD

**Issue by GreenKudu** [ThijsRay/podimo#20]
Hi,

I'm trying to access a Spanish Podimo Podcast to no avail. I assumed that by just using the provided NL/DE locales it would just work, but apparently not. An error is being returned when fetching the initial token in the getPreregisterToken() function, which is baffling me since it is very early in the login process. I also tried adding 'es' to the supported locales in the config file, but the error remains.

Any clue on what could be going on here?

```
AuthorizationPreregisterUser
An error occurred: 403, message='Forbidden', url=URL('https://podimo.com/graphql')
```

**Comment by ThijsRay** [comment]
Unfortunately, the tool has temporarily been blocked by Podimo and/or Cloudflare. That is likely why you are seeing 403 Forbidden errors. The code base has to be modified to work around this blockade, but I'm not yet sure how to do this. If you have any suggestions, feel free to open an issue or submit a pull request!

**Comment by ThijsRay** [comment]
Hi @GreenKudu, do you still experience this issue? The latest version ([v0.3.0](https://github.com/ThijsRay/podimo/releases/tag/v0.3.0)) should resolve it for now.

**Comment by thajesta** [comment]
Hi @ThijsRay, I pulled the latest version and it works again for me.
