### ISSUE TITLE
ImportError: cannot import name 'url_quote' from 'werkzeug.urls' 

### ISSUE THREAD

**Issue by sauerhosen** [ThijsRay/podimo#22]
Hi @ThijsRay -- Docker image of v0.3.1 fails with following error (will test v0.3.0 later). v0.2.2 with GIJS' solution for cloudfare proxy worked fine.  

> podimo  | Traceback (most recent call last):
> podimo  |   File "/src/main.py", line 28, in <module>
> podimo  |     from quart import Quart, Response, render_template, request
> podimo  |   File "/usr/local/lib/python3.10/site-packages/quart/__init__.py", line 5, in <module>
> podimo  |     from .app import Quart as Quart
> podimo  |   File "/usr/local/lib/python3.10/site-packages/quart/app.py", line 46, in <module>
> podimo  |     from werkzeug.urls import url_quote
> podimo  | ImportError: cannot import name 'url_quote' from 'werkzeug.urls' (/usr/local/lib/python3.10/site-packages/werkzeug/urls.py)
> podimo exited with code 1

**Comment by ThijsRay** [comment]
Good that you mention this! It looks like https://pypi.org/project/Werkzeug/ was updated today and it has introduced some breaking changes. This is a dependency of quart, one of the libraries that is used. I'll try to pin the dependencies to a specific version.

**Comment by ThijsRay** [comment]
This has been fixed in [v0.3.2](https://github.com/ThijsRay/podimo/releases/tag/v0.3.2). Thanks for reporting it!
