### ISSUE TITLE
Is the demo website podimo.thijs.sh up to date?

### ISSUE THREAD

**Issue by alego500** [ThijsRay/podimo#35]
I've noticed there's been a lot of updates recently and I presume the service is working again, so my question is is the the demo website up-to-date because it doesn't work for me so before self hosting I'd like to know if the service is working as expected at the moment.

**Comment by ThijsRay** [comment]
Unfortunately the demo website doesn't work because it generates too much traffic to the Podimo servers. Self hosting on a small scale works fine though.
