### ISSUE TITLE
Issues since Feb 10/15, single user or bigger issue

### ISSUE THREAD

**Issue by sjcjonker** [ThijsRay/podimo#37]
Dear followers of this Repo,

Wanted to check I have some issues, and I'm not sure if this is a single user issue or a wider one. Can somebody share, with or without local credentials (tested both), and scraperAPI whether they experience the same errors?

The below error started at Feb 10:
Feb 14 23:34:05 mon podimo.py[364770]: ERROR | 2024-02-14T23:34:05Z | Error while fetching podcasts: Podimo returned an error code. Response code was: 401 for query "query ChannelEpisodesQuery($po..."

Then on the 15th this changed to:
Feb 15 04:51:11 mon podimo.py[364770]: ERROR | 2024-02-15T04:51:11Z | An error occurred: Podimo returned an error code. Response code was: 401 for query "query AuthorizationPreregister..."

Only noticed it just now, because the weekly podcast from Podimo was missing :-)
Happy to bring out the proxies etc and do my utmost best to find the issue and create a pull request in the next week or so, but wanted to check if I should focus on user / account issues and/or the wider. 

Thanks

**Comment by midasvo** [comment]
Have you checked the ScraperAPI dashboard, multiple users have reported their accounts having issues. If so write to their support or create a new account.

**Comment by sjcjonker** [comment]
Thx closing issue.
