### ISSUE TITLE
Feat: Fetch more episodes and combine them in the RSS feed

### ISSUE THREAD

**Issue by leonvsc** [ThijsRay/podimo#38]
Hi!

It seems like since the last release you can only fetch 100 episodes instead of 500 episodes due to API changes from Podimo.

I did some research and if you change the offset in the API call to Podimo in the GetPodcasts function in client.py you can get different episodes.

As example: if you change the offset to 100 with a limit of 100, you get episode 100 till 200.

There should be a way to combine multiple requests to the API to fetch all the episodes and get them in the RSS feed. Maybe you have some ideas about it to implement this?

**Comment by midasvo** [comment]
Have also been running into this. I am implementing an offset queryparam so I can at least fetch histories.

**Comment by jhogervorst** [comment]
I've implemented this and opened a PR: https://github.com/ThijsRay/podimo/pull/40

**Comment by leonvsc** [comment]
It seems to be working after PR #40. Thanks @jhogervorst!

Issue can be closed.
