### ISSUE TITLE
Any chance you could push the newest version to docker?

### ISSUE THREAD

**Issue by Frosbe** [ThijsRay/podimo#42]
It seems the docker container is still on an old version, could you update it, thanks :)

**Comment by ThijsRay** [comment]
I have been trying to do so, but [GitHub Actions](https://github.com/ThijsRay/podimo/actions/runs/9098433756/job/25008601710) keeps failing because it runs out of memory. I'll try to figure out what is causing that.

**Comment by Frosbe** [comment]
Ahh,  i see, thanks
