### ISSUE TITLE
Only shows 99 episode

### ISSUE THREAD

**Issue by SolidRhino** [ThijsRay/podimo#5]
This code shows only 99 episodes even though the podcast has more episodes. Is there a way to fix this?

**Comment by ThijsRay** [comment]
Sure! This is defined at https://github.com/ThijsRay/podimo/blob/f2e810daee53542deae26701916470fbdb3c36ac/main.py#L353
but it can be changed if you prefer. I put an arbitrary limit of 100 in there, but it can be anything.

**Comment by ThijsRay** [comment]
I have increased the limit to 500, hopefully that is enough!

**Comment by SolidRhino** [comment]
Thank you 😄
