### ISSUE TITLE
Can you add this feature?

### ISSUE THREAD

**Issue by SolidRhino** [ThijsRay/podimo#6]
I don't like that my login and password are visual in the URL. Can you add a feature like [this fork](https://github.com/jonathanjuursema/podimo-to-rss)? Where he puts the username and password in the docker file.

**Comment by ThijsRay** [comment]
I can see why this is useful for a privately hosted instance of this script, but I don't think that this will add anything for the public instance I'm hosting. I won't be implementing this myself but feel free to open a pull request!
