### ISSUE TITLE
Podcasts larger than 100 episodes has problems.

### ISSUE THREAD

**Issue by SolidRhino** [ThijsRay/podimo#7]
When I try to add Man Man Man de podcast, Pom or the zelfspodcast there is no XML returning. And the podcast can't be found. When I add another podcast that has less than 100 episodes, there are no errors.

**Comment by ThijsRay** [comment]
I am aware of the issue. Podimo has changed a few things in their API which the script does not account for yet. I will adjust the script later but it is not very high on my priority list.

**Comment by ThijsRay** [comment]
Issue is resolved!
