### ISSUE TITLE
Something went wrong while fetching the podcasts

### ISSUE THREAD

**Issue by STX2k** [ThijsRay/podimo#8]
Hi ThijsRay, 
I have been using your script for a while now and wanted to generate a few new feeds. But, no matter which show I take I always get the same error. `Something went wrong while fetching the podcasts` 

https://podimo.com/de/shows/88ab00dd-b85d-45a6-93c4-6d58d83201c9
https://podimo.com/de/shows/d9070421-3ab1-4c29-ab71-d6564f1b782e

First I thought that there may have been changes to the API and Podimo have introduced Geo blocking, changed the locale from nl-NL to de-DE, but did not help. Old generated feeds still seem to work, because 2 days ago an episode was downloaded. 

Had now tested the script once locally to exclude that your IP was perhaps blacklisted. But that does not seem to be the problem. Do you have similar problems?

Edit: Now i see in my logfile this error:

```
Error while fetching podcasts: {'message': 'User does not have enough privilege', 'locations': [{'line': 29, 'column': 3}], 'path': ['episodes', 0, 'streamMedia'], 'code': 'forbidden', 'extensions': {'exception': {'code': 'forbidden', 'message': 'User does not have enough privilege'}}}
```

i had only test it with 1 show from local and got a forbidden? I see you make an commit to fix this but is there maybe more changes on the podimo api?

Greets

**Comment by ThijsRay** [comment]
I am aware of the issue. Podimo changed more than I initially thought so I will have to reverse engineer the app again. This takes some time and is not a major priority for me at this moment.

**Comment by ThijsRay** [comment]
Issue is resolved! Their API is more strict than before which is why the "User does not have enough privilege" exception was triggered on Podimo's side. The script imitates the Android app a bit better now.
