### ISSUE TITLE
Which program's do you use?

### ISSUE THREAD

**Issue by SolidRhino** [ThijsRay/podimo#9]
Which program's do you use to reverse engineer the API?

**Comment by ThijsRay** [comment]
I install a fresh copy of the Podimo Android app and perform a man-in-the-middle attack to capture all the traffic that is generated by the app. Reversing the API becomes much easier once you know what traffic is being sent and received.

I have used
- [apk-mitm](https://github.com/shroudedcode/apk-mitm) to enable the app to accept my self-signed certificate
- [frida-android-unpinning](https://github.com/httptoolkit/frida-android-unpinning) (basically the same as the above but without having to patch the app itself)
- [mitmproxy](https://mitmproxy.org/) to capture and decrypt the traffic
- [PCAPdroid](https://github.com/emanuele-f/PCAPdroid) to send the Podimo app traffic to the mitmproxy

**Comment by joep-nl** [comment]
You could also use Postman to capture HTTP requests with a proxy. This works also on iOS.
